x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 20m
      max-file: "3"

services:
  dex:
    image: ${DEX_DOCKER_TAG}:${DEX_DOCKET_TAG}
    restart: unless-stopped
    stop_grace_period: 5m
    command:
      - dex
      - serve
      - /config.yaml
    volumes:
      - ./dex/config.yaml:/config.yaml:ro
    <<: *logging
    labels:
      - traefik.enable=true
      - traefik.http.routers.${DEX_HOST}.service=${DEX_HOST}
      - traefik.http.routers.${DEX_HOST}.entrypoints=websecure
      - traefik.http.routers.${DEX_HOST}.rule=Host(`${DEX_HOST}.${DOMAIN}`)
      - traefik.http.routers.${DEX_HOST}.tls.certresolver=letsencrypt
      - traefik.http.routers.${DEX_HOST}lb.service=${DEX_HOST}
      - traefik.http.routers.${DEX_HOST}lb.entrypoints=websecure
      - traefik.http.routers.${DEX_HOST}lb.rule=Host(`${DEX_LB}.${DOMAIN}`)
      - traefik.http.routers.${DEX_HOST}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${DEX_HOST}.loadbalancer.server.port=${DEX_PORT:-5556}
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=${DEX_PORT:-5556}
      - metrics.instance=babylon
      - metrics.network=canton-${MIGRATION_ID}
