x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 20m
      max-file: "3"

services:
  validator-init:
    restart: "no"
    image: ${PG_DOCKER_REPO:-postgres}:${PG_DOCKER_TAG:-16-bookworm}
    environment:
      - POSTGRES_USER=${PG_USER:-postgres}
      - PGPASSWORD=${PG_PASSWORD:-postgres}
      - PG_NODE=${PG_NODE:-canton-postgres}
      - PG_PORT=${PG_PORT:-5432}
      - PG_VALIDATOR_DB=validator_${MIGRATION_ID}
    <<: *logging
    command: >
      sh -c 'until psql -h "$$PG_NODE" -p $$PG_PORT -U "$$POSTGRES_USER" -c "select 1" >/dev/null 2>&1; do
        echo "Waiting for PostgreSQL at $$PG_NODE:$$PG_PORT..."; sleep 2;
      done;
      if ! psql -h "$$PG_NODE" -p $$PG_PORT --username "$$POSTGRES_USER" -tAc "SELECT 1 FROM pg_database WHERE datname = '\''$$PG_VALIDATOR_DB'\''" | grep -q 1; then
        psql -h "$$PG_NODE" -p $$PG_PORT --username "$$POSTGRES_USER" -c "CREATE DATABASE \"$$PG_VALIDATOR_DB\"";
      fi'
  validator:
    image: "${VALIDATOR_DOCKER_REPO}:${VALIDATOR_DOCKER_TAG}"
    environment:
      - SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_URL=${AUTH_WELLKNOWN_URL}
      - SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_CLIENT_ID=${VALIDATOR_AUTH_CLIENT_ID}
      - SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_CLIENT_SECRET=${VALIDATOR_AUTH_CLIENT_SECRET}
      - SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_AUDIENCE=${LEDGER_API_AUTH_AUDIENCE}
      - SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_SCOPE=${LEDGER_API_AUTH_SCOPE:-}
      - SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_USER_NAME=${LEDGER_API_ADMIN_USER}
      - SPLICE_APP_VALIDATOR_WALLET_USER_NAME=${VALIDATOR_WALLET_ADMIN}
      - SPLICE_APP_VALIDATOR_AUTH_AUDIENCE=${VALIDATOR_AUTH_AUDIENCE}
      - SPLICE_APP_VALIDATOR_AUTH_JWKS_URL=${AUTH_JWKS_URL}
      - SPLICE_APP_VALIDATOR_PARTICIPANT_ADDRESS=participant
      - SPLICE_APP_VALIDATOR_SV_SPONSOR_ADDRESS=${SPONSOR_SV_ADDRESS}
      - SPLICE_APP_VALIDATOR_ONBOARDING_SECRET=${ONBOARDING_SECRET}
      - SPLICE_APP_VALIDATOR_SCAN_ADDRESS=${SCAN_ADDRESS}
      - SPLICE_APP_VALIDATOR_PARTICIPANT_IDENTIFIER=${PARTICIPANT_IDENTIFIER}
      - SPLICE_APP_VALIDATOR_PARTY_HINT=${PARTY_HINT}
      - SPLICE_APP_CONTACT_POINT=${CONTACT_POINT}
      - JAVA_TOOL_OPTIONS=-XX:+UseG1GC -XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=75 -Dscala.concurrent.context.minThreads=8 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/persistent-data -Dio.netty.noPreferDirect=true
      - |
        ADDITIONAL_CONFIG_PERSISTENCE=
            canton.validator-apps.validator_backend.storage {
              type = postgres
              config {
                dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
                properties = {
                  databaseName = validator_${MIGRATION_ID}
                  currentSchema = validator
                  serverName = ${PG_NODE}
                  portNumber = ${PG_PORT}
                  user = ${PG_USER}
                  password = ${PG_PASSWORD}
                  tcpKeepAlive = true
                }
              }
            }
      - |
        ADDITIONAL_CONFIG_APP_INSTANCES=
          canton.validator-apps.validator_backend.app-instances={}
      - |
        ADDITIONAL_CONFIG_BFT_SCAN=
          canton.validator-apps.validator_backend.scan-client.type = "bft"
          canton.validator-apps.validator_backend.scan-client.seed-urls = [ "${SCAN_ADDRESS}" ]
      - |
        ADDITIONAL_CONFIG_MIGRATION_ID=
            canton.validator-apps.validator_backend {
              domain-migration-id = ${MIGRATION_ID}
            }
      - |
        ADDITIONAL_CONFIG_TOPUPS=
          canton.validator-apps.validator_backend.domains.global.buy-extra-traffic.target-throughput = ${TRAFFIC_TOPUP_THROUGHPUT}
          canton.validator-apps.validator_backend.domains.global.buy-extra-traffic.min-topup-interval = ${TRAFFIC_TOPUP_INTERVAL}
    restart: unless-stopped
    <<: *logging
    depends_on:
      validator-init:
        condition: service_completed_successfully
    labels:
      - traefik.enable=true
      - traefik.http.routers.${VALIDATOR_HOST}.service=${VALIDATOR_HOST}
      - traefik.http.routers.${VALIDATOR_HOST}.entrypoints=websecure
      - traefik.http.routers.${VALIDATOR_HOST}.rule=Host(`${VALIDATOR_HOST}.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.${VALIDATOR_HOST}.tls.certresolver=letsencrypt
      - traefik.http.routers.${VALIDATOR_HOST}lb.service=${VALIDATOR_HOST}
      - traefik.http.routers.${VALIDATOR_HOST}lb.entrypoints=websecure
      - traefik.http.routers.${VALIDATOR_HOST}lb.rule=Host(`${KEYCLOAK_LB}.${DOMAIN}`)
      - traefik.http.routers.${VALIDATOR_HOST}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${VALIDATOR_HOST}.loadbalancer.server.port=5003
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=10013
      - metrics.instance=validator
      - metrics.network=canton-${MIGRATION_ID}
    volumes:
      - domain-upgrade-dump:/domain-upgrade-dump

  wallet-ui:
    image: "${WALLET_UI_DOCKER_REPO}:${WALLET_UI_DOCKER_TAG}"
    environment:
      - SPLICE_APP_UI_AUTH_AUDIENCE=${VALIDATOR_AUTH_AUDIENCE}
      - SPLICE_APP_UI_AUTH_CLIENT_ID=${WALLET_UI_CLIENT_ID}
      - SPLICE_APP_UI_AUTH_URL=${AUTH_URL}
      - SPLICE_APP_UI_HTTP_URL=false
      - SPLICE_APP_UI_NETWORK_NAME=${WALLET_UI_NETWORK_NAME}
      - SPLICE_APP_UI_NETWORK_FAVICON_URL=${WALLET_UI_NETWORK_FAVICON_URL}
      - SPLICE_APP_UI_AMULET_NAME=${WALLET_UI_AMULET_NAME}
      - SPLICE_APP_UI_AMULET_NAME_ACRONYM=${WALLET_UI_AMULET_NAME_ACRONYM}
      - SPLICE_APP_UI_NAME_SERVICE_NAME=${WALLET_UI_NAME_SERVICE_NAME}
      - SPLICE_APP_UI_NAME_SERVICE_NAME_ACRONYM=${WALLET_UI_NAME_SERVICE_NAME_ACRONYM}
    <<: *logging
    labels:
      - traefik.enable=true
      - traefik.http.routers.${VALIDATOR_HOST}-wallet.service=${VALIDATOR_HOST}-wallet
      - traefik.http.routers.${VALIDATOR_HOST}-wallet.entrypoints=websecure
      - traefik.http.routers.${VALIDATOR_HOST}-wallet.rule=Host(`${VALIDATOR_HOST}.${DOMAIN}`)
      - traefik.http.routers.${VALIDATOR_HOST}-wallet.tls.certresolver=letsencrypt
      - traefik.http.routers.${VALIDATOR_HOST}-walletlb.service=${VALIDATOR_HOST}-wallet
      - traefik.http.routers.${VALIDATOR_HOST}-walletlb.entrypoints=websecure
      - traefik.http.routers.${VALIDATOR_HOST}-walletlb.rule=Host(`${KEYCLOAK_LB}.${DOMAIN}`)
      - traefik.http.routers.${VALIDATOR_HOST}-walletlb.tls.certresolver=letsencrypt
      - traefik.http.services.${VALIDATOR_HOST}-wallet.loadbalancer.server.port=8080

volumes:
  domain-upgrade-dump:
