{{- if .Values.keycloak.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}-keycloak-ingress
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - host: {{ .Values.keycloak.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "helm.fullname" . }}-keycloak-service
            port:
              name: http
{{- end }}
