apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}-validator-ingress
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: {{ .Values.validator.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "helm.fullname" . }}-validator
                port:
                  name: wallet-ui
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ include "helm.fullname" . }}-validator
                port:
                  name: api
