{{- if .Values.dex.enabled }}
{{- $dexSecret := lookup "v1" "Secret" .Release.Namespace .Values.auth.existingSecret }}
{{- $clientSecret := index $dexSecret.data .Values.auth.validator_client_secret_key | b64dec }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-dex-config
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |-
    issuer: {{ .Values.dex.issuer }}

    storage:
      type: memory

    web:
      http: 0.0.0.0:{{ .Values.dex.port }}

    oauth2:
      responseTypes: ["code", "token", "id_token"]
      skipApprovalScreen: true
      allowedOrigins:
        - {{ .Values.dex.allowedOrigin }}

    staticClients:
      - id: validator-app
        secret: {{ $clientSecret }}
        name: "Validator App"
        public: false

      - id: wallet-ui
        name: "Canton Wallet UI"
        redirectURIs:
          - "{{ .Values.dex.clients.wallet.callback }}"
        public: true

    enablePasswordDB: true

    staticPasswords:
{{ toYaml .Values.dex.staticPasswords | nindent 6 }}
{{- end }}
