apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-validator-secret
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
  onboarding_secret: {{ .Values.validator.onboarding_secret | b64enc }}
