{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-keycloak-service
  labels:
    app: {{ include "helm.fullname" . }}-keycloak-service
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "helm.fullname" . }}-keycloak
  ports:
    - port: {{ .Values.keycloak.port }}
      targetPort: {{ .Values.keycloak.port }}
      name: http
{{- end }}
