apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-postgresql
  labels:
    app: {{ include "helm.fullname" . }}-postgresql
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "helm.fullname" . }}-postgresql
  ports:
    - port: {{ .Values.db.port }}
      targetPort: 5432
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
