apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-validator
  labels:
    app: {{ include "helm.fullname" . }}-validator
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "helm.fullname" . }}-validator
  ports:
    - name: api
      port: 5003
      targetPort: 5003
    - name: metrics
      port: 10013
      targetPort: 10013
    - name: wallet-ui
      port: 8080
      targetPort: 8080
