issuer: http://sso.example.com

storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:
  - id: validator-app
    secret: validator-app-secret
    name: "Validator App"
    public: false

  - id: wallet-ui
    name: "Canton Wallet UI"
    redirectURIs:
      - "http://wallet.example.com"
    public: true

enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    hash: "$2y$10$z5x3bI.1VdMX7jVQz5sm0eq1vE0yAaC3Z38B6V2SMKrAFMghDgYiO" # # bcrypt admin123
    username: "admin"
    userID: "admin"  # Will appear in the JWT as `sub`
